tasks:
  - name: setup_env
    cmd: bash setup_env.sh

  - name: preprocess
    cmd: python preprocess.py

  - name: train
    cmd: python train.py
    depends_on:
      - preprocess
      - setup_env

  - name: evaluate
    cmd: python evaluate.py
    depends_on:
      - train
    ignore_failed_dependencies: true
